[package]
name = "bad_keys_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.2"
wgpu = "0.13.1"
pollster = "0.2"
crossbeam = "0.8.2"
fastrand = "1.7.0"